var keys = module.exports = {}
//####################################################### CRICKET KEYS ##########################################
keys.CC_MATCH_LINEUPS = "zfcache:CC_MATCH_LINEUPS"
keys.FB_MATCH_LINEUPS = "zfcache:FB_MATCH_LINEUPS"
keys.KB_MATCH_LINEUPS = "zfcache:KB_MATCH_LINEUPS"
keys.BS_MATCH_LINEUPS = "zfcache:BS_MATCH_LINEUPS"
keys.BK_MATCH_LINEUPS = "zfcache:BK_MATCH_LINEUPS"
keys.ACCESS_TOKEN = "ACCESS_TOKEN",
keys.USER_TEAMS_MODEL = "USER_TEAMS_MODEL",
keys.USER_TEAMS_MODEL_POST_MATCH = "USER_TEAMS_MODEL_POST_MATCH"
// keys.USER_CRICKET_TEAM = "USER_CRICKET_TEAM"
// keys.CRICKET_ACTIVE_MATCHES = "CRICKET_ACTIVE_MATCHES"
keys.CRICKET_ACTIVE_MATCHES = "zfcache:MATCH_MODEL"
keys.CRICKET_PROMOBANNERS = "CRICKET_PROMOBANNERS"
keys.CRICKET_ANNOUNCEMENTS = "CRICKET_ANNOUNCEMENTS"
keys.CRICKET_MATCH_DETAILS = "CRICKET_MATCH_DETAILS"
keys.CRICKET_CLOSING_MATCH_DETAILS = "zfcache:MATCH_DETAILS"
keys.QUIZ_CACHED = "zfcache:QUIZ_CACHED"
// keys.CRICKET_LEAGUES = "CRICKET_LEAGUES"
keys.CRICKET_LEAGUES = "zfcache:LEAGUE_MODEL"
keys.JOINED_LEAGUES = "JOINED_LEAGUES"
keys.JOINED_LEAGUES_COUNT = "JOINED_LEAGUES_COUNT"
keys.CRICKET_JOINED_LEAGUES = "CRICKET_JOINED_LEAGUES"
keys.CRICKET_JOINED_TEAM = "CRICKET_JOINED_TEAM"
keys.CRICKET_TEAM_PREVIEW = "CRICKET_TEAM_PREVIEW"
keys.CRICKET_PLAYERS = "zfcache:SEASSON_PLAYERS"
keys.KABADDI_PLAYERS = "KABADDI_PLAYERS"
keys.CRICKET_JOINED_LEAGUES_MATCHES = "zfcache:CRICKET_JOINED_LEAGUES_MATCHES"
keys.CRIC_JOINED_LEAGUES = "CRIC_JOINED_LEAGUES"
keys.CRIC_LEAGUES = "CRIC_LEAGUES"
keys.CRIC_TEAM_DETAILS = "CRIC_TEAM_DETAILS"
keys.CRIC_TXN_HISTORY = "CRIC_TXN_HISTORY"
keys.CRIC_WALLET_DETAILS = "CRIC_WALLET_DETAILS"
keys.USER_NOTIFICATION = "USER_NOTIFICATION"
keys.USER_TXN_WIHDRAW = "USER_TXN_WIHDRAW"
keys.USER_TICKETS = "USER_TICKETS"
keys.USER_PROMOTIONS = "USER_PROMOTIONS"
keys.TEAM_COUNT = "TEAM_COUNT"
keys.PROMOTION_HOME_BANNER = "zfcache:PROMOTION_HOME_BANNER"
keys.PROMOTION_BANNER = "zfcache:PROMOTION_BANNER"
keys.CONFIG_REDIS = "zfcache:CONFIG_REDIS"
//####################################################### CRICKET KEYS ##########################################







//####################################################### FOOTBALL KEYS ##########################################
keys.FOOTBALL_ACTIVE_MATCHES = "FOOTBALL_ACTIVE_MATCHES"
keys.BASKETBALL_ACTIVE_MATCHES = "BASKETBALL_ACTIVE_MATCHES"
keys.BASKETBALL_PROMOBANNERS = "BASKETBALL_PROMOBANNERS"
keys.BASKETBALL_ANNOUNCEMENTS = "BASKETBALL_ANNOUNCEMENTS"
keys.BASKETBALL_ACTIVE_QUIZES = "BASKETBALL_ACTIVE_QUIZES"
keys.BASKETBALL_MATCH_DETAIL = "BASKETBALL_MATCH_DETAIL"
keys.BASKETBALL_LEAGUES = "BASKETBALL_LEAGUES"
keys.BASKETBALL_ANNOUNCEMENTS = "BASKETBALL_ANNOUNCEMENTS"
keys.BASKETBALL_JOINED_LEAGUES_MATCHES = "BASKETBALL_JOINED_LEAGUES_MATCHES"
keys.BASKETBALL_ANNOUNCEMENTS = "BASKETBALL_ANNOUNCEMENTS"
keys.BASKETBALL_PLAYERS = "BASKETBALL_PLAYERS"
keys.BK_JOINED_LEAGUES = "BK_JOINED_LEAGUES"
keys.BK_LEAGUES = "BK_LEAGUES"
keys.KABADDI_ACTIVE_MATCHES = "KABADDI_ACTIVE_MATCHES"
keys.FOOTBALL_PROMOBANNERS = "FOOTBALL_PROMOBANNERS"
keys.FOOTBALL_ANNOUNCEMENTS = "FOOTBALL_ANNOUNCEMENTS",
keys.FOOTBALL_MATCH_DETAILS = "FOOTBALL_MATCH_DETAILS"
keys.FOOTBALL_LEAGUES = "FOOTBALL_LEAGUES"
//####################################################### FOOTBALL KEYS ##########################################






//####################################################### JABADDI KEYS ##########################################
keys.KABADDI_PROMOBANNERS = "KABADDI_PROMOBANNERS"
keys.KABADDI_ANNOUNCEMENTS = "KABADDI_ANNOUNCEMENTS"
keys.KABADDI_MATCH_DETAILS = "KABADDI_MATCH_DETAILS"
keys.KABADDI_LEAGUES = "KABADDI_LEAGUES"
keys.BASEBALL_ACTIVE_MATCHES = "BASEBALL_ACTIVE_MATCHES"
keys.BASEBALL_PROMOBANNERS = "BASEBALL_PROMOBANNERS"
keys.BASEBALL_ANNOUNCEMENTS = "BASEBALL_ANNOUNCEMENTS"
keys.BASEBALL_JOINED_LEAGUES_MATCHES = "BASEBALL_JOINED_LEAGUES_MATCHES"
keys.BASEBALL_PLAYERS = "BASEBALL_PLAYERS"
keys.BASEBALL_MATCH_DETAIL = "BASEBALL_MATCH_DETAIL"
keys.BASEBALL_LEAGUES = "BASEBALL_LEAGUES"
keys.BASEBALL_JOINED_LEAGUES = "BASEBALL_JOINED_LEAGUES"
//####################################################### JABADDI KEYS ##########################################