var SequelizeAuto = require('sequelize-auto')
    // var auto = new SequelizeAuto('database', 'user', 'pass');
var fs = require('fs');
var path = require('path');
var auto = new SequelizeAuto(process.env.DB, process.env.USERT, process.env.PASSWORD, {
    host: process.env.HOST,
    dialect: 'mysql',
    directory: true, // prevents the program from writing to disk
    port:3306,
    additional: {
        timestamps: false
    },
    tables: ["bb_acknowledge", "bb_admin", "bb_admin_cash_added", "bb_admin_permissions", "bb_admins_roles", "bb_affiliate_joinings", "bb_affiliate_stats", "bb_affiliates", "bb_amount_per_date", "bb_announcements", "bb_app_update", "bb_bank_details", "bb_bonanza_affiliate_status", "bb_bonus_stats", "bb_campaign", "bb_campaign_codes", "bb_closed_user_leagues_0", "bb_closed_user_leagues_1", "bb_closed_user_leagues_2", "bb_closed_user_teams_0", "bb_closed_user_teams_1", "bb_closed_user_teams_2", "bb_configs", "bb_countries", "bb_credit_stats", "bb_cron_mails", "bb_generator", "bb_how_to_play", "bb_is_playing", "bb_jobs", "bb_jobs_data", "bb_key_generator", "bb_kyc_attempts", "bb_landing_match", "bb_leaderboard_matches", "bb_leaderboards", "bb_leaders", "bb_leaders_2", "bb_leaders_2_main", "bb_leaders_3", "bb_leaders_3_main", "bb_leaders_main", "bb_league_categories", "bb_league_template_groups", "bb_league_templates", "bb_league_templates_data", "bb_league_templates_old", "bb_leagues", "bb_leagues_data", "bb_leagues_old", "bb_live_scores", "bb_master_analytics_data", "bb_match_add_errors", "bb_match_balls", "bb_match_category", "bb_matches", "bb_matches_croned", "bb_mobile_otp", "bb_notifications", "bb_otp_match", "bb_pan_details", "bb_password_reset", "bb_payment_config", "bb_payout_otp", "bb_player_credits", "bb_player_selected", "bb_player_selection_counts", "bb_player_selections", "bb_players", "bb_playing22", "bb_promo_contents", , "bb_promotion_codes", "bb_promotion_stats", "bb_promotions", "bb_referral_stats", "bb_refund_history", "bb_roles_permissions", "bb_season_players", "bb_season_teams", "bb_seasonal_points", "bb_seasons", "bb_signup_promos", "bb_task_id", "bb_teams", "bb_ticket_users", "bb_tickets", "bb_txn", "bb_upcoming_matches", "bb_upcoming_matches_cricket", "bb_upcoming_matches_entity", "bb_user_devices", "bb_user_extras", "bb_user_leagues", "bb_user_leagues_dump", "bb_user_leagues_removed", "bb_user_rakes", "bb_user_rakes_by_match", "bb_user_records", "bb_user_records_copy_final", "bb_user_reportings", "bb_user_teams", "bb_user_teams_dump", "bb_user_teams_ip", "bb_user_teams_lookup", "bb_users", "bb_users_removed", "bb_verify_email", "bb_withdrawal_records", "bb_withdrawals", "branch_event_tracking", "cron_auto_withdraw", "oauth_access_tokens", "oauth_access_tokens_dump", "oauth_authorization_codes", "oauth_clients", "oauth_jwt", "oauth_refresh_tokens", "oauth_scopes", "oauth_users"]
})
// auto.run(function(err) {
//     if (err) throw err;
//     // console.log(auto.tables); // table list
//     // console.log(auto.foreignKeys); // foreign key list
//     auto.write(, auto.tables);
// });

// bb_aadhaar_details,bb_acknowledge,bb_admin,bb_admin_cash_added,bb_admin_permissions,bb_admins_roles,bb_affiliate_joinings,bb_affiliate_stats,bb_affiliates,bb_amount_per_date,bb_announcements,bb_app_update,bb_bank_details,bb_bonanza_affiliate_status,bb_bonus_stats,bb_campaign,bb_campaign_codes,bb_closed_user_leagues_0,bb_closed_user_leagues_1,bb_closed_user_leagues_2,bb_closed_user_teams_0,bb_closed_user_teams_1,bb_closed_user_teams_2,bb_configs,bb_countries,bb_credit_stats,bb_cron_mails,bb_generator,bb_how_to_play,bb_is_playing,bb_jobs, bb_jobs_data,bb_key_generator,bb_kyc_attempts,bb_landing_match,bb_leaderboard_matches,bb_leaderboards,bb_leaders,bb_leaders_2,bb_leaders_2_main,bb_leaders_3,bb_leaders_3_main,bb_leaders_main,bb_league_categories,bb_league_template_groups,bb_league_templates,bb_league_templates_data,bb_league_templates_old,bb_leagues,bb_leagues_data,bb_leagues_old,bb_live_scores,bb_master_analytics_data,bb_match_add_errors,bb_match_balls,bb_match_category,bb_matches,bb_matches_croned,bb_mobile_otp,bb_notifications,bb_otp_match,bb_pan_details,bb_password_reset,bb_payment_config,bb_payout_otp,bb_player_credits,bb_player_selected,bb_player_selection_counts,bb_player_selections,bb_players,bb_playing22,bb_promo_contents,bb_promotion_codes,bb_promotion_stats,bb_promotions,bb_referral_stats,bb_refund_history,bb_roles_permissions,bb_season_players,bb_season_teams,bb_seasonal_points,bb_seasons,bb_signup_promos,bb_task_id,bb_teams,bb_ticket_users,bb_tickets,bb_txn,bb_upcoming_matches,bb_upcoming_matches_cricket,bb_upcoming_matches_entity,bb_user_devices,bb_user_extras,bb_user_leagues,bb_user_leagues_dump,bb_user_leagues_removed,bb_user_rakes,bb_user_rakes_by_match,bb_user_records,bb_user_records_copy_final,bb_user_reportings,bb_user_teams,bb_user_teams_dump,bb_user_teams_ip,bb_user_teams_lookup,bb_users,bb_users_removed,bb_verify_email,bb_withdrawal_records,bb_withdrawals,branch_event_tracking,cron_auto_withdraw,oauth_access_tokens,oauth_access_tokens_dump,oauth_authorization_codes,oauth_clients,oauth_jwt,oauth_refresh_tokens,oauth_scopes,oauth_users